apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: ghost-db
spec:
  crVersion: 1.14.0
  secretsName: ghost-db-secrets
  upgradeOptions:
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 1
    image: percona/percona-xtradb-cluster:8.0.32-24.2
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 2Gi
  haproxy:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:1.14.0-haproxy
    serviceType: ClusterIP
