apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/ghost
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    # Базові налаштування беруться з charts/ghost/values.yaml
    # Тут ми нічого не переписуємо, бо Base і є нашим дефолтом (Staging-like)
