apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 5m
  chart:
    spec:
      # --- ВАЖЛИВА ЗМІНА ---
      # Ми кажемо Flux брати чарт з Git-репозиторію, а не з Helm-репозиторію
      chart: ./charts/ghost
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      # ---------------------
  values:
    # Передаємо реальні налаштування
    env:
      url: "http://ghost-staging.k8s.com822.dom" # Це заміниться в Staging
      database__connection__host: "ghost-db-haproxy"
      database__connection__user: "root"
      database__connection__database: "ghost_data"
    
    image:
      repository: ghost
      tag: 5.130.5-alpine