apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: staging
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: mariadb
      version: 19.1.0  
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h0m0s

  values:
    image:
      tag: latest 
      pullPolicy: Always
 
    fullnameOverride: mariadb

    
    auth:
      rootPassword: "VerySecretRootPass123!"
      database: "ghost"
      username: "ghost"
      password: "VerySecretUserPass123!"

    
    primary:
      persistence:
        enabled: true
        size: 2Gi
       
---
# 3. MariaDB для PRODUCTION (Додаємо цей блок)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: production
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: mariadb
      version: 19.1.0  
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h0m0s
  values:
    image:
      tag: latest  
      pullPolicy: Always
    fullnameOverride: mariadb
    auth:
     
      rootPassword: "VerySecretRootPass123!"
      database: "ghost"
      username: "ghost"
      password: "VerySecretUserPass123!"
    primary:
      persistence:
        enabled: true
        size: 5Gi 
       
