apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: infrastructure
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb
      version: "19.x.x" # Bitnami версія
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infrastructure
  values:
    # Standalone - одна нода, без кластеризації Galera. Швидко і надійно.
    architecture: standalone

    auth:
      rootPassword: "root_password"
      database: "ghost_db"
      username: "ghost"
      password: "ghost_password"

    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      # Фікс для безпеки (щоб не сварився PodSecurity)
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 1001
