apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: infrastructure
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: "latest" # Можна вказати конкретну версію або залишити свіжу
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      rootUser: admin
      rootPassword: "MySuperSecretPassword123" # У реальному проді це має бути Secret

    # Вимикаємо розподілений режим (нам вистачить однієї репліки для лаби)
    mode: standalone

    persistence:
      enabled: true
      size: 1Gi
      storageClass: longhorn # Використовуємо наш сторедж

    # Створюємо бакет автоматично при старті
    defaultBuckets: "ghost-bucket"

    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001
