apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
#     version: "latest" # Можна вказати конкретну версію або залишити свіжу
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    rootUser: admin
    rootPassword: "admin" # У реальному проді це має бути Secret

    # Вимикаємо розподілений режим (нам вистачить однієї репліки для лаби)
    mode: standalone

    persistence:
      enabled: true
      size: 2Gi
      storageClass: longhorn # Використовуємо наш сторедж

    # Створюємо бакет автоматично при старті
    defaultBuckets: "ghost-bucket"

    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001
    resources:
      requests:
        memory: 128Mi  # "Я займу зовсім трошки місця, чесно!"
        cpu: 100m
      limits:
        memory: 1Gi    # "Але якщо буде вільно - візьму гігабайт"
        cpu: 1000m
