apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pxc-operator-global-admin
subjects:
  - kind: ServiceAccount
    name: pxc-operator             # Або flux-system-pxc-operator (перевір точну назву SA)
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
