---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: percona
  namespace: flux-system
spec:
  interval: 1h
  url: https://percona.github.io/percona-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: pxc-operator
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values:
    watchNamespace: ""
